version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./front
    volumes:
      - /app/node_modules
      - ./front:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3106:80"

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./back
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./back:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: jaehyeon
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306

  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: app_mysql
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: jaehyeon
      MYSQL_DATABASE: myapp
